### ISSUE TITLE
Metric creation is unclear.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/MonitoringBundle#23]
After trying to create metric i get `Metric with name 'date_metric' was not found.`

Here is my class.

``` php
namespace ONGR\DemoBundle\Metrics;

use ONGR\MonitoringBundle\Metric\MetricInterface;

/**
 * Class DateMetric.
 */
class DateMetric implements MetricInterface
{
    /**
     * {@inheritdoc}
     */
    public function getValue()
    {
        return new \DateTime();
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'date_metric';
    }
}
```

This is my configs.

``` yaml
ongr_monitoring:
    es_manager: monitoring
    commands:
        commands:
            - ongr:monitoring:metrics:collect
    metric_collector:
        metrics:
            document_count:
                - { name: foo, document: es.manager.default.product }
            date_metric:
                - { name: date_metric, document: es.manager.default.product }

services:
    ongr_demo.metric.date:
        class: ONGR\DemoBundle\Metrics\DateMetric
        tags:
            - { name: ongr_monitoring.metric, metric: date_metric }
```
